### ISSUE TITLE
primaryKey should be array

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/the-el#1]
In the `users.json` example, it looks like `primaryKey` is set to a string value, rather than an array. [The spec](http://specs.frictionlessdata.io/table-schema/#properties-optional) says it's an array, assumedly to support compound keys. Unless I'm misunderstanding.

**Comment by awm33** [comment]
@timwis It can be either a string or array of strings

**Comment by awm33** [comment]
@timwis Looks like that was true. They changed it for v1, but didn't place that in the [changelog](http://specs.frictionlessdata.io/changelog/) :/. The library that the library we're using for the-el still allows for this, which is why it's not throwing an error. We also don't need to use `fmt:` in the datetime format with the newer version of the lib.

**Comment by awm33** [comment]
I fixed the PK for the example
